M48
; DRILL file {KiCad 9.0.0} date 2025-09-30T20:45:14+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-30T20:45:14+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C1.500
%
G90
G05
T1
X130.5Y-94.18
X130.5Y-96.72
T2
X123.5Y-94.23
X123.5Y-96.77
T3
X134.75Y-93.25
X134.75Y-97.75
X141.25Y-93.25
X141.25Y-97.75
T4
X147.2Y-95.5
X168.0Y-95.5
M30
